plugins {
    id 'java'
    id 'application'
    id 'com.gradleup.shadow' version '8.3.5'
}

group 'com.example'
version '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

dependencies {
    implementation 'net.portswigger.burp.extensions:montoya-api:2023.9'
}

shadowJar {
    archiveBaseName.set('NewJSLink')
    archiveClassifier.set('')
    archiveVersion.set('')
}
